<?php

namespace Database\Seeders;

use App\Models\Agent;
use App\Models\Bus;
use App\Models\Crew;
use App\Models\CrewPosition;
use App\Models\Location;
use App\Models\Route;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrewSeeder extends Seeder
{
    public function run(): void
    {
        // ── 1. Crew Positions (jabatan) ─────────────────────────────────
        $positions = [
            ['name' => 'Pengemudi Utama',  'base_allowance' => 3500000],
            ['name' => 'Pengemudi Cadangan','base_allowance' => 3000000],
            ['name' => 'Kondektur',         'base_allowance' => 2500000],
            ['name' => 'Teknisi Armada',    'base_allowance' => 2800000],
            ['name' => 'Koordinator Awak',  'base_allowance' => 4000000],
        ];

        foreach ($positions as $pos) {
            CrewPosition::updateOrCreate(['name' => $pos['name']], $pos);
        }

        $posIds    = CrewPosition::pluck('id', 'name');
        $agentId   = Agent::value('id');
        $locationId= Location::value('id');
        $busId     = Bus::value('id');
        $routeId   = Route::value('id');

        // ── 2. Clear existing crew data ─────────────────────────────────
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('crews')->delete();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        // ── 3. Seed 24 crew members across 6 regions ───────────────────
        $crewData = [
            // ── REGION: JAWA TIMUR ──────────────────────────────────────
            [
                'nik'              => '3578011501850001',
                'employee_number'  => 'EMP-2019-001',
                'name'             => 'Agus Santoso',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1985-01-15',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Raya Kenjeran No.45, Surabaya',
                'current_address'  => 'Jl. Raya Kenjeran No.45, Surabaya',
                'domicile_city'    => 'Surabaya',
                'phone_number'     => '081234567001',
                'contact_phone_1'  => '082345678001',
                'contact_phone_2'  => '083456789001',
                'license_number'   => 'SIM-B2-001-2020',
                'license_expired_at'=> '2026-01-15',
                'rank'             => 'Senior',
                'spouse_name'      => 'Siti Rahayu',
                'children_count'   => 2,
                'join_date'        => '2019-03-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Timur',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '3578021203900002',
                'employee_number'  => 'EMP-2020-002',
                'name'             => 'Bambang Widodo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1990-03-12',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Bratang Binangun No.10, Surabaya',
                'current_address'  => 'Jl. Bratang Binangun No.10, Surabaya',
                'domicile_city'    => 'Surabaya',
                'phone_number'     => '081234567002',
                'contact_phone_1'  => '082345678002',
                'contact_phone_2'  => '083456789002',
                'license_number'   => 'SIM-B2-002-2021',
                'license_expired_at'=> '2027-03-12',
                'rank'             => 'Madya',
                'spouse_name'      => 'Dewi Lestari',
                'children_count'   => 1,
                'join_date'        => '2020-06-15',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Timur',
                'position'         => 'Kondektur',
            ],
            [
                'nik'              => '3571030507880003',
                'employee_number'  => 'EMP-2018-003',
                'name'             => 'Cahyo Purnomo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1988-07-05',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. Semampir Tengah No.22, Malang',
                'current_address'  => 'Jl. Semampir Tengah No.22, Malang',
                'domicile_city'    => 'Malang',
                'phone_number'     => '081234567003',
                'contact_phone_1'  => '082345678003',
                'contact_phone_2'  => '083456789003',
                'license_number'   => 'SIM-B2-003-2019',
                'license_expired_at'=> '2025-07-05',
                'rank'             => 'Senior',
                'spouse_name'      => 'Rina Setyawati',
                'children_count'   => 3,
                'join_date'        => '2018-01-10',
                'education'        => 'D3',
                'status'           => 'active',
                'region'           => 'Jawa Timur',
                'position'         => 'Koordinator Awak',
            ],
            [
                'nik'              => '3507041809920004',
                'employee_number'  => 'EMP-2022-004',
                'name'             => 'Doni Firmansyah',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1992-09-18',
                'religion'         => 'Islam',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'AB',
                'original_address' => 'Jl. Besar Nganjuk No.5, Nganjuk',
                'current_address'  => 'Jl. Besar Nganjuk No.5, Nganjuk',
                'domicile_city'    => 'Nganjuk',
                'phone_number'     => '081234567004',
                'contact_phone_1'  => '082345678004',
                'contact_phone_2'  => '083456789004',
                'license_number'   => 'SIM-B2-004-2022',
                'license_expired_at'=> '2028-09-18',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2022-04-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Timur',
                'position'         => 'Pengemudi Cadangan',
            ],

            // ── REGION: JAWA TENGAH ──────────────────────────────────────
            [
                'nik'              => '3372050210870005',
                'employee_number'  => 'EMP-2017-005',
                'name'             => 'Eko Prasetyo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1987-10-02',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Pemuda No.88, Semarang',
                'current_address'  => 'Jl. Pemuda No.88, Semarang',
                'domicile_city'    => 'Semarang',
                'phone_number'     => '081234567005',
                'contact_phone_1'  => '082345678005',
                'contact_phone_2'  => '083456789005',
                'license_number'   => 'SIM-B2-005-2018',
                'license_expired_at'=> '2026-10-02',
                'rank'             => 'Senior',
                'spouse_name'      => 'Endah Wulandari',
                'children_count'   => 2,
                'join_date'        => '2017-07-17',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Tengah',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '3372062511910006',
                'employee_number'  => 'EMP-2021-006',
                'name'             => 'Fajar Nugroho',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1991-11-25',
                'religion'         => 'Kristen',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Gajahmada No.34, Semarang',
                'current_address'  => 'Jl. Gajahmada No.34, Semarang',
                'domicile_city'    => 'Semarang',
                'phone_number'     => '081234567006',
                'contact_phone_1'  => '082345678006',
                'contact_phone_2'  => '083456789006',
                'license_number'   => 'SIM-B2-006-2021',
                'license_expired_at'=> '2027-11-25',
                'rank'             => 'Madya',
                'spouse_name'      => 'Yeni Octavia',
                'children_count'   => 1,
                'join_date'        => '2021-01-04',
                'education'        => 'D3',
                'status'           => 'active',
                'region'           => 'Jawa Tengah',
                'position'         => 'Kondektur',
            ],
            [
                'nik'              => '3312070811890007',
                'employee_number'  => 'EMP-2019-007',
                'name'             => 'Gunawan Saputra',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1989-08-08',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. Masjid No.12, Klaten',
                'current_address'  => 'Jl. Masjid No.12, Klaten',
                'domicile_city'    => 'Klaten',
                'phone_number'     => '081234567007',
                'contact_phone_1'  => '082345678007',
                'contact_phone_2'  => '083456789007',
                'license_number'   => 'SIM-B2-007-2020',
                'license_expired_at'=> '2026-08-08',
                'rank'             => 'Senior',
                'spouse_name'      => 'Hartatik',
                'children_count'   => 2,
                'join_date'        => '2019-09-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Tengah',
                'position'         => 'Teknisi Armada',
            ],
            [
                'nik'              => '3322080505940008',
                'employee_number'  => 'EMP-2023-008',
                'name'             => 'Hendra Kurniawan',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1994-05-05',
                'religion'         => 'Islam',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Diponegoro No.7, Purwokerto',
                'current_address'  => 'Jl. Diponegoro No.7, Purwokerto',
                'domicile_city'    => 'Purwokerto',
                'phone_number'     => '081234567008',
                'contact_phone_1'  => '082345678008',
                'contact_phone_2'  => '083456789008',
                'license_number'   => 'SIM-B2-008-2023',
                'license_expired_at'=> '2029-05-05',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2023-03-15',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Tengah',
                'position'         => 'Pengemudi Cadangan',
            ],

            // ── REGION: DI YOGYAKARTA ──────────────────────────────────
            [
                'nik'              => '3471010101860009',
                'employee_number'  => 'EMP-2016-009',
                'name'             => 'Irwan Hadisuryo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1986-01-01',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Malioboro No.11, Yogyakarta',
                'current_address'  => 'Jl. Malioboro No.11, Yogyakarta',
                'domicile_city'    => 'Yogyakarta',
                'phone_number'     => '081234567009',
                'contact_phone_1'  => '082345678009',
                'contact_phone_2'  => '083456789009',
                'license_number'   => 'SIM-B2-009-2017',
                'license_expired_at'=> '2025-01-01',
                'rank'             => 'Senior',
                'spouse_name'      => 'Sumarni',
                'children_count'   => 3,
                'join_date'        => '2016-08-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'D.I. Yogyakarta',
                'position'         => 'Koordinator Awak',
            ],
            [
                'nik'              => '3471021503930010',
                'employee_number'  => 'EMP-2021-010',
                'name'             => 'Joko Susilo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1993-03-15',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. Kaliurang KM 7, Sleman',
                'current_address'  => 'Jl. Kaliurang KM 7, Sleman',
                'domicile_city'    => 'Sleman',
                'phone_number'     => '081234567010',
                'contact_phone_1'  => '082345678010',
                'contact_phone_2'  => '083456789010',
                'license_number'   => 'SIM-B2-010-2021',
                'license_expired_at'=> '2027-03-15',
                'rank'             => 'Madya',
                'spouse_name'      => 'Sari Dewi',
                'children_count'   => 1,
                'join_date'        => '2021-05-10',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'D.I. Yogyakarta',
                'position'         => 'Pengemudi Utama',
            ],

            // ── REGION: JAWA BARAT ──────────────────────────────────────
            [
                'nik'              => '3273011212870011',
                'employee_number'  => 'EMP-2018-011',
                'name'             => 'Kurniawan Hidayat',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1987-12-12',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'AB',
                'original_address' => 'Jl. Asia Afrika No.55, Bandung',
                'current_address'  => 'Jl. Asia Afrika No.55, Bandung',
                'domicile_city'    => 'Bandung',
                'phone_number'     => '081234567011',
                'contact_phone_1'  => '082345678011',
                'contact_phone_2'  => '083456789011',
                'license_number'   => 'SIM-B2-011-2019',
                'license_expired_at'=> '2025-12-12',
                'rank'             => 'Senior',
                'spouse_name'      => 'Nurul Hidayah',
                'children_count'   => 2,
                'join_date'        => '2018-02-01',
                'education'        => 'D3',
                'status'           => 'active',
                'region'           => 'Jawa Barat',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '3273020310910012',
                'employee_number'  => 'EMP-2020-012',
                'name'             => 'Lukman Hakim',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1991-10-03',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Soekarno-Hatta No.201, Bandung',
                'current_address'  => 'Jl. Soekarno-Hatta No.201, Bandung',
                'domicile_city'    => 'Bandung',
                'phone_number'     => '081234567012',
                'contact_phone_1'  => '082345678012',
                'contact_phone_2'  => '083456789012',
                'license_number'   => 'SIM-B2-012-2020',
                'license_expired_at'=> '2026-10-03',
                'rank'             => 'Madya',
                'spouse_name'      => 'Fitri Rahayu',
                'children_count'   => 1,
                'join_date'        => '2020-11-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Barat',
                'position'         => 'Kondektur',
            ],
            [
                'nik'              => '3204030405930013',
                'employee_number'  => 'EMP-2022-013',
                'name'             => 'Muhamad Rizal',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1993-04-04',
                'religion'         => 'Islam',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Raya Cirebon No.30, Cirebon',
                'current_address'  => 'Jl. Raya Cirebon No.30, Cirebon',
                'domicile_city'    => 'Cirebon',
                'phone_number'     => '081234567013',
                'contact_phone_1'  => '082345678013',
                'contact_phone_2'  => '083456789013',
                'license_number'   => 'SIM-B2-013-2022',
                'license_expired_at'=> '2028-04-04',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2022-08-17',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Jawa Barat',
                'position'         => 'Pengemudi Cadangan',
            ],

            // ── REGION: BANTEN / DKI JAKARTA ────────────────────────────
            [
                'nik'              => '3671041506860014',
                'employee_number'  => 'EMP-2015-014',
                'name'             => 'Nanang Priambodo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1986-06-15',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. Raya Serang No.100, Tangerang',
                'current_address'  => 'Jl. Raya Serang No.100, Tangerang',
                'domicile_city'    => 'Tangerang',
                'phone_number'     => '081234567014',
                'contact_phone_1'  => '082345678014',
                'contact_phone_2'  => '083456789014',
                'license_number'   => 'SIM-B2-014-2016',
                'license_expired_at'=> '2026-06-15',
                'rank'             => 'Senior',
                'spouse_name'      => 'Laila Khusna',
                'children_count'   => 3,
                'join_date'        => '2015-01-02',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Banten',
                'position'         => 'Koordinator Awak',
            ],
            [
                'nik'              => '3172050202900015',
                'employee_number'  => 'EMP-2021-015',
                'name'             => 'Okta Hermawan',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1990-02-02',
                'religion'         => 'Kristen',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Cempaka Putih No.17, Jakarta Pusat',
                'current_address'  => 'Jl. Cempaka Putih No.17, Jakarta Pusat',
                'domicile_city'    => 'Jakarta Pusat',
                'phone_number'     => '081234567015',
                'contact_phone_1'  => '082345678015',
                'contact_phone_2'  => '083456789015',
                'license_number'   => 'SIM-B2-015-2021',
                'license_expired_at'=> '2027-02-02',
                'rank'             => 'Madya',
                'spouse_name'      => 'Maria Susanti',
                'children_count'   => 2,
                'join_date'        => '2021-03-01',
                'education'        => 'D3',
                'status'           => 'active',
                'region'           => 'DKI Jakarta',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '3671061709950016',
                'employee_number'  => 'EMP-2023-016',
                'name'             => 'Panji Wicaksono',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1995-09-17',
                'religion'         => 'Islam',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Kihajar Dewantara No.3, Cilegon',
                'current_address'  => 'Jl. Kihajar Dewantara No.3, Cilegon',
                'domicile_city'    => 'Cilegon',
                'phone_number'     => '081234567016',
                'contact_phone_1'  => '082345678016',
                'contact_phone_2'  => '083456789016',
                'license_number'   => 'SIM-B2-016-2023',
                'license_expired_at'=> '2029-09-17',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2023-07-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Banten',
                'position'         => 'Kondektur',
            ],

            // ── REGION: LAMPUNG / SUMATERA ───────────────────────────────
            [
                'nik'              => '1871012011840017',
                'employee_number'  => 'EMP-2014-017',
                'name'             => 'Qomarudin Effendi',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1984-11-20',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'AB',
                'original_address' => 'Jl. Raden Intan No.55, Bandar Lampung',
                'current_address'  => 'Jl. Raden Intan No.55, Bandar Lampung',
                'domicile_city'    => 'Bandar Lampung',
                'phone_number'     => '081234567017',
                'contact_phone_1'  => '082345678017',
                'contact_phone_2'  => '083456789017',
                'license_number'   => 'SIM-B2-017-2015',
                'license_expired_at'=> '2025-11-20',
                'rank'             => 'Senior',
                'spouse_name'      => 'Wati Supriati',
                'children_count'   => 4,
                'join_date'        => '2014-01-06',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Lampung',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '1871030109920018',
                'employee_number'  => 'EMP-2022-018',
                'name'             => 'Rendi Saputra',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1992-09-01',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. ZA Pagar Alam No.8, Bandar Lampung',
                'current_address'  => 'Jl. ZA Pagar Alam No.8, Bandar Lampung',
                'domicile_city'    => 'Bandar Lampung',
                'phone_number'     => '081234567018',
                'contact_phone_1'  => '082345678018',
                'contact_phone_2'  => '083456789018',
                'license_number'   => 'SIM-B2-018-2022',
                'license_expired_at'=> '2028-09-01',
                'rank'             => 'Madya',
                'spouse_name'      => 'Susi Indriani',
                'children_count'   => 1,
                'join_date'        => '2022-02-14',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Lampung',
                'position'         => 'Teknisi Armada',
            ],
            [
                'nik'              => '1604041408970019',
                'employee_number'  => 'EMP-2023-019',
                'name'             => 'Syahrul Rahman',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1997-08-14',
                'religion'         => 'Islam',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'A',
                'original_address' => 'Jl. S. Parman No.22, Palembang',
                'current_address'  => 'Jl. S. Parman No.22, Palembang',
                'domicile_city'    => 'Palembang',
                'phone_number'     => '081234567019',
                'contact_phone_1'  => '082345678019',
                'contact_phone_2'  => '083456789019',
                'license_number'   => 'SIM-B2-019-2023',
                'license_expired_at'=> '2029-08-14',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2023-10-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'Sumatera Selatan',
                'position'         => 'Pengemudi Cadangan',
            ],

            // ── BONUS DATA (wanita & variasi status) ────────────────────
            [
                'nik'              => '3578040714910020',
                'employee_number'  => 'EMP-2020-020',
                'name'             => 'Tari Anggraini',
                'gender'           => 'Perempuan',
                'birth_date'       => '1991-07-14',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Panglima Sudirman No.77, Surabaya',
                'current_address'  => 'Jl. Panglima Sudirman No.77, Surabaya',
                'domicile_city'    => 'Surabaya',
                'phone_number'     => '081234567020',
                'contact_phone_1'  => '082345678020',
                'contact_phone_2'  => '083456789020',
                'license_number'   => 'SIM-B1-020-2020',
                'license_expired_at'=> '2026-07-14',
                'rank'             => 'Madya',
                'spouse_name'      => 'Budi Santoso',
                'children_count'   => 1,
                'join_date'        => '2020-08-01',
                'education'        => 'S1',
                'status'           => 'active',
                'region'           => 'Jawa Timur',
                'position'         => 'Kondektur',
            ],
            [
                'nik'              => '3273050602880021',
                'employee_number'  => 'EMP-2019-021',
                'name'             => 'Udin Kusnandar',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1988-02-06',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'O',
                'original_address' => 'Jl. Dago No.45, Bandung',
                'current_address'  => 'Jl. Dago No.45, Bandung',
                'domicile_city'    => 'Bandung',
                'phone_number'     => '081234567021',
                'contact_phone_1'  => '082345678021',
                'contact_phone_2'  => '083456789021',
                'license_number'   => 'SIM-B2-021-2019',
                'license_expired_at'=> '2025-02-06',
                'rank'             => 'Senior',
                'spouse_name'      => 'Cucu Rohayati',
                'children_count'   => 2,
                'join_date'        => '2019-04-01',
                'education'        => 'SMA/SMK',
                'status'           => 'on_leave',
                'region'           => 'Jawa Barat',
                'position'         => 'Teknisi Armada',
            ],
            [
                'nik'              => '3372060510960022',
                'employee_number'  => 'EMP-2022-022',
                'name'             => 'Vera Kusumawati',
                'gender'           => 'Perempuan',
                'birth_date'       => '1996-10-05',
                'religion'         => 'Kristen',
                'marital_status'   => 'Lajang',
                'blood_type'       => 'B',
                'original_address' => 'Jl. Pandanaran No.9, Semarang',
                'current_address'  => 'Jl. Pandanaran No.9, Semarang',
                'domicile_city'    => 'Semarang',
                'phone_number'     => '081234567022',
                'contact_phone_1'  => '082345678022',
                'contact_phone_2'  => '083456789022',
                'license_number'   => 'SIM-B1-022-2022',
                'license_expired_at'=> '2028-10-05',
                'rank'             => 'Junior',
                'spouse_name'      => null,
                'children_count'   => 0,
                'join_date'        => '2022-06-20',
                'education'        => 'S1',
                'status'           => 'active',
                'region'           => 'Jawa Tengah',
                'position'         => 'Kondektur',
            ],
            [
                'nik'              => '3471070714830023',
                'employee_number'  => 'EMP-2013-023',
                'name'             => 'Wahyu Tri Nugroho',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1983-07-14',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'A',
                'original_address' => 'Jl. Solo KM 9, Yogyakarta',
                'current_address'  => 'Jl. Solo KM 9, Yogyakarta',
                'domicile_city'    => 'Yogyakarta',
                'phone_number'     => '081234567023',
                'contact_phone_1'  => '082345678023',
                'contact_phone_2'  => '083456789023',
                'license_number'   => 'SIM-B2-023-2014',
                'license_expired_at'=> '2026-07-14',
                'rank'             => 'Senior',
                'spouse_name'      => 'Dwi Astuti',
                'children_count'   => 3,
                'join_date'        => '2013-12-01',
                'education'        => 'SMA/SMK',
                'status'           => 'active',
                'region'           => 'D.I. Yogyakarta',
                'position'         => 'Pengemudi Utama',
            ],
            [
                'nik'              => '1871080211900024',
                'employee_number'  => 'EMP-2021-024',
                'name'             => 'Yarno Sulistyo',
                'gender'           => 'Laki-laki',
                'birth_date'       => '1990-11-02',
                'religion'         => 'Islam',
                'marital_status'   => 'Menikah',
                'blood_type'       => 'AB',
                'original_address' => 'Jl. Yos Sudarso No.40, Bandar Lampung',
                'current_address'  => 'Jl. Yos Sudarso No.40, Bandar Lampung',
                'domicile_city'    => 'Bandar Lampung',
                'phone_number'     => '081234567024',
                'contact_phone_1'  => '082345678024',
                'contact_phone_2'  => '083456789024',
                'license_number'   => 'SIM-B2-024-2021',
                'license_expired_at'=> '2027-11-02',
                'rank'             => 'Madya',
                'spouse_name'      => 'Listia Amalia',
                'children_count'   => 2,
                'join_date'        => '2021-09-15',
                'education'        => 'D3',
                'status'           => 'active',
                'region'           => 'Lampung',
                'position'         => 'Koordinator Awak',
            ],
        ];

        foreach ($crewData as $data) {
            $positionName = $data['position'];
            unset($data['position']);

            Crew::create(array_merge($data, [
                'crew_position_id' => $posIds[$positionName] ?? null,
                'agent_id'         => $agentId,
                'pool_id'          => $locationId,
                'bus_id'           => $busId,
                'route_id'         => $routeId,
                'photo_path'       => null,
            ]));
        }

        $this->command->info('✓ Seeded ' . count($crewData) . ' crew members across 6 regions.');
    }
}
